[build]
builder = "NIXPACKS"
buildCommand = "cd backend && rm -rf dist node_modules && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm run start:prod"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
